In [35]:
import numpy as np

ar = np.array([[1,2,3],[1,2,3]])
# print(ar)
ar=  ar.transpose()
print(ar)
br = np.array([1,2])
# print(br)
# br = br.transpose()
br = br.reshape(2,-1)
print(br)
print(ar.shape,br.shape)


[[1 1]
 [2 2]
 [3 3]]
[[1]
 [2]]
(3, 2) (2, 1)


In [26]:
print(ar.dot(br))

[[3]
 [6]
 [9]]


In [10]:
ar.shape
print(ar.reshape(-1))
print(ar.flatten())

[1 2 3 1 2 3]
[1 2 3 1 2 3]
